# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mrq_widget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(541, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.question_widget = QtWidgets.QWidget(self.centralwidget)
        self.question_widget.setGeometry(QtCore.QRect(30, 120, 481, 431))
        self.question_widget.setAutoFillBackground(False)
        self.question_widget.setStyleSheet("border: 1px solid gray")
        self.question_widget.setObjectName("question_widget")
        self.time_display = QtWidgets.QLCDNumber(self.centralwidget)
        self.time_display.setGeometry(QtCore.QRect(390, 10, 111, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(252, 0, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 0, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 0, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.time_display.setPalette(palette)
        self.time_display.setObjectName("time_display")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 90, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 30, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.question_no_label = QtWidgets.QLabel(self.centralwidget)
        self.question_no_label.setGeometry(QtCore.QRect(120, 90, 60, 16))
        self.question_no_label.setObjectName("question_no_label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(350, 90, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.marks_label = QtWidgets.QLabel(self.centralwidget)
        self.marks_label.setGeometry(QtCore.QRect(450, 90, 60, 16))
        self.marks_label.setObjectName("marks_label")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 20, 61, 16))
        self.label_6.setObjectName("label_6")
        self.current_status = QtWidgets.QLabel(self.centralwidget)
        self.current_status.setGeometry(QtCore.QRect(80, 20, 171, 16))
        self.current_status.setObjectName("current_status")
        self.rtsp_url = QtWidgets.QLabel(self.centralwidget)
        self.rtsp_url.setGeometry(QtCore.QRect(30, 40, 171, 16))
        self.rtsp_url.setObjectName("rtsp_url")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 60, 221, 16))
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 541, 22))
        self.menubar.setObjectName("menubar")
        self.menuCS3103_Group_11_Exam_Software = QtWidgets.QMenu(self.menubar)
        self.menuCS3103_Group_11_Exam_Software.setObjectName("menuCS3103_Group_11_Exam_Software")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuCS3103_Group_11_Exam_Software.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Questions:"))
        self.label_2.setText(_translate("MainWindow", "Time Left:"))
        self.question_no_label.setText(_translate("MainWindow", "1 of 3"))
        self.label_4.setText(_translate("MainWindow", "Marks:"))
        self.marks_label.setText(_translate("MainWindow", "1"))
        self.label_6.setText(_translate("MainWindow", "Status:"))
        self.current_status.setText(_translate("MainWindow", "You are streaming"))
        self.rtsp_url.setText(_translate("MainWindow", "rtsp://{IP_ADDRESS}:{PORT}"))
        self.label_9.setText(_translate("MainWindow", "Send this link to your examiner."))
        self.menuCS3103_Group_11_Exam_Software.setTitle(_translate("MainWindow", "CS3103 Group 11 Exam Software"))

    def addQuestionWidget(widget):
        self.question_widget = widget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    sys.exit(app.exec_())
