# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mrq.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.question_label = QtWidgets.QLabel(Form)
        self.question_label.setGeometry(QtCore.QRect(50, 20, 321, 51))
        self.question_label.setObjectName("question_label")
        self.option_1_checkbox = QtWidgets.QCheckBox(Form)
        self.option_1_checkbox.setGeometry(QtCore.QRect(60, 90, 87, 20))
        self.option_1_checkbox.setObjectName("option_1_checkbox")
        self.option_2_checkbox = QtWidgets.QCheckBox(Form)
        self.option_2_checkbox.setGeometry(QtCore.QRect(60, 130, 87, 20))
        self.option_2_checkbox.setObjectName("option_2_checkbox")
        self.option_3_checkbox = QtWidgets.QCheckBox(Form)
        self.option_3_checkbox.setGeometry(QtCore.QRect(60, 170, 87, 20))
        self.option_3_checkbox.setObjectName("option_3_checkbox")
        self.option_4_checkbox = QtWidgets.QCheckBox(Form)
        self.option_4_checkbox.setGeometry(QtCore.QRect(60, 210, 87, 20))
        self.option_4_checkbox.setObjectName("option_4_checkbox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Q:"))
        self.question_label.setText(_translate("Form", "Question"))
        self.option_1_checkbox.setText(_translate("Form", "Option 1"))
        self.option_2_checkbox.setText(_translate("Form", "Option 2"))
        self.option_3_checkbox.setText(_translate("Form", "Option 3"))
        self.option_4_checkbox.setText(_translate("Form", "Option 4"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
